src/components/cards/treemap/Cell.vue
src/components/global/Footer.vue
src/components/global/Topbar.vue
src/plugins/vuetify.ts
src/views/Results.vue

Signed-off-by: Aaron Lippold <lippold@gmail.com>

Minor color fixes pushing to 1.0

---

src/components/cards/controltable/ControlRowDetails.vue
src/sass/main.scss

Completely Fix #45 using scss, still unsure why we could not throw highlighting under the component.

Chrome code highlighting final

---

package-lock.json
package.json
src/components/global/upload_tabs/FileReader.vue
src/plugins/vuetify.ts
src/store/report_intake.ts

Add vue toasted library and have it throw toasts on failed file uploads.
Signed-off-by: Luke Malinowski <lmalinowski@mitre.org>

ENH: Add vue toast support Fix #64 #65

---

src/components/cards/ProfileData.vue
src/components/global/upload_tabs/S3Reader.vue
src/views/Results.vue

Renders the profile dependency chain(s) of the actively loaded file(s)
#47

Profile view

---

src/components/cards/controltable/ControlRowHeader.vue
src/components/cards/controltable/ResponsiveRowLarge.vue

Fixed styling issues on Control Table

---

src/components/cards/controltable/ControlRowDetails.vue

Made zebra table look better in light mode

---

src/components/global/AboutModal.vue

Fixed repeat version in about modal. Fix #96

---

package-lock.json
package.json
src/components/cards/controltable/ControlRowDetails.vue
src/components/cards/controltable/ControlRowHeader.vue

Fixed exception messages, as well as status dropdown size

---

src/store/app_info.ts
vue.config.js

Fix issue #78 - adds more app info to vuex store

---

src/store/app_info.ts

Fix re-broken version

---

src/components/global/Sidebar.vue

Fix #102 - Sidebar now has an all-files button

---

src/components/global/ExportCaat.vue
src/components/global/Sidebar.vue
src/views/BaseView.vue
src/views/Results.vue

Also, better formatting on the result column (to not say PASSED when it's a fail, etc.)
Fixes #101

Export CAAT now respects filters.

---

package-lock.json
package.json
src/components/cards/controltable/ControlTable.vue

Improved scrolling of control table. This shouldn't be auto merged.

---

src/plugins/vuetify.ts

Made notifications require manual dismiss

---

package-lock.json
package.json
src/main.ts
src/types/vue-analytics.d.ts
tsconfig.json

Created new branch to clean up merge conflicts from original googleAnalytics branch

adding google analytics functionality

---

src/components/cards/controltable/ControlRowDetails.vue

Signed-off-by: Luke Malinowski <lmalinowski@mitre.org>

BUG: Fix console.logs on status_color

---

.eslintrc.js

Disabled no-console error flag in eslintrc

---

src/components/cards/controltable/ControlRowHeader.vue

Replaced control table nist tags with full versions

---

src/components/cards/StatusCardRow.vue
src/components/cards/controltable/ControlRowCol.vue
src/components/cards/controltable/ControlRowDetails.vue
src/components/cards/controltable/ControlRowHeader.vue
src/sass/main.scss

Fixes #143 
Fixes #139 
Fixes #135
Fixes #90

Cleanup for HL2.0

---

src/components/global/Topbar.vue
src/components/global/UploadNexus.vue
src/utilities/helper_util.ts
src/views/Results.vue

Tab sliders + url validation

---

.github/workflows/CHANGELOG.yml
.github/workflows/VERSION.yml
.github/workflows/gh-pages.yml
package.json

Signed-off-by: Aaron Lippold <lippold@gmail.com>

- fixed issues in the GH Actions
